*******************************************************************************
****** ADDFX1_lvt schematic lab1_sj_v2  <vs>  ADDFX1_lvt layout lab1_sj_v2
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45n1lvt) MOS                                   14      14
(g45p1lvt) MOS                                   14      14
                                             ------  ------
Total                                            28      28

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1lvt) MOS                                   14      14           2       2
(g45p1lvt) MOS                                   14      14           2       2
(g45n1lvt:ParMos2#1) MosBlk                       -       -           1       1
(g45n1lvt:ParMos3#1) MosBlk                       -       -           1       1
(g45n1lvt:SerMos2#1) MosBlk                       -       -           1       1
(g45n1lvt:SerMos3#1) MosBlk                       -       -           3       3
(g45p1lvt:ParMos2#1) MosBlk                       -       -           1       1
(g45p1lvt:ParMos3#1) MosBlk                       -       -           1       1
(g45p1lvt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1lvt:SerMos3#1) MosBlk                       -       -           3       3
                                             ------  ------      ------  ------
Total                                            28      28          16      16

Schematic and Layout Match
