###############################################################
#  Generated by:      Cadence Innovus 22.33-s094_1
#  OS:                Linux x86_64(Host ID c4d3)
#  Generated on:      Mon May 18 18:10:32 2026
#  Design:            mgmt_core_wrapper
#  Command:           create_clock_tree_spec -out_file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Common UI
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_db clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_db port:core_clk .cts_is_sdc_clock_root true

# Clocks present at pin core_clk
#   myclock (period 4.000ns) in timing_config default_emulate_constraint_mode([/home/alumnes/s/serik.perez/dnd/synth/caravel-picorv32/R1/DBS/placed/libs/mmmc/default_emulate_constraint_mode.sdc.gz])
create_clock_tree -name myclock -source core_clk -no_skew_group
set_db clock_tree:myclock .cts_clock_tree_source_output_max_transition_time_early -index delay_corner:default_emulate_delay_corner 0.015
set_db clock_tree:myclock .cts_clock_tree_source_output_max_transition_time_late -index delay_corner:default_emulate_delay_corner 0.015
# Clock period setting for source pin of myclock
set_db port:core_clk .cts_clock_period 4

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_db cts_timing_connectivity_info {}

# Skew group to balance non generated clock:myclock in timing_config:default_emulate_constraint_mode (sdc /home/alumnes/s/serik.perez/dnd/synth/caravel-picorv32/R1/DBS/placed/libs/mmmc/default_emulate_constraint_mode.sdc.gz)
create_skew_group -name myclock/default_emulate_constraint_mode -sources core_clk -auto_sinks
set_db skew_group:myclock/default_emulate_constraint_mode .cts_skew_group_include_source_latency true
set_db skew_group:myclock/default_emulate_constraint_mode .cts_skew_group_created_from_clock myclock
set_db skew_group:myclock/default_emulate_constraint_mode .cts_skew_group_created_from_constraint_modes {default_emulate_constraint_mode  }
set_db skew_group:myclock/default_emulate_constraint_mode .cts_skew_group_created_from_delay_corners default_emulate_delay_corner


check_clock_tree_convergence
# Restore the ILM status if possible
if { [get_db ccopt_auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

